spring: 
  profiles: 
    active: 
    - dev
---
server: 
  port: 8001
spring: 
  profiles: dev
  application: 
    name: config-dept-client
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: password
  url: jdbc:mysql://192.168.80.130:3306/cloudBD01?useSSL=false&allowMultiQueries=true
  dbcp2:
    min-idle: 5
    initial-size: 5
    max-total: 5 
    max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.cloud.entities
  mapper-locations: classpath:mybatis/mapper/*.xml

eureka: 
  client:
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
  instance: 
    instance-id: dept-8001.com
    prefer-ip-address: true

info: 
  app.name: config01
  company.name: www.move.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server: 
  port: 8001
spring: 
  profiles: test
  application: 
    name: config-dept-client
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: password
  url: jdbc:mysql://192.168.80.130:3306/cloudBD01?useSSL=false&allowMultiQueries=true
  dbcp2:
    min-idle: 5
    initial-size: 5
    max-total: 5 
    max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.cloud.entities
  mapper-locations: classpath:mybatis/mapper/*.xml

eureka: 
  client:
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
  instance: 
    instance-id: dept-8001.com
    prefer-ip-address: true

info: 
  app.name: config02  
  company.name: www.move.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$